#设置thymeleaf的模板
spring:
  thymeleaf:
    mode: HTML
#设置活跃的配置文件
  profiles:
    active: dev
#设置缓存
    cache: false
#设置可以访问thymeleaf下的页面
#  resources:
#    static-locations: classpath:/templates/
#    add-mappings: false

#  设置静态资源访问
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
  mvc:
    throw-exception-if-no-handler-found: true

